parameters:
  documentsFormId: 1500
  # for edit config action
  documents_editable_config_params:
    - 'documentsFormId'
    
services:
  _defaults:
    autowire: true
    public: true

  YesWiki\Documents\Service\:
    resource: 'services/*'

